#! /bin/sh
#
# Set the number of workspaces
bspc monitor -d 1 2 3 4 5 6

# Launch keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Window configurations
bspc config border_width         0
bspc config window_gap          16
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Padding outside of the window
bspc config top_padding            60
bspc config bottom_padding         60
bspc config left_padding           60
bspc config right_padding          60

# Move floating windows
bspc config pointer_action1 move

# Resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Floating windows
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a KeePassXC state=floating center=true rectangle=909x625+0+0
bspc rule -a feh state=floating center=true
bspc rule -a galculator state=floating
bspc rule -a Peek state=floating follow=on

## Set desktops
killall -qw chrome
killall -qw tmux
killall -qw emacsclient
killall -qw slack
killall -qw cider
killall -qw btop
killall -qw pcmanfm

# Set background and top bar
feh --bg-scale $HOME/.local/share/img/wallpaper/active
systemctl --user start polybar

sleep .25

# Launch these when script runs
# -o option means "one shot", meaning the rule goes away after launching the app

# Wait for the network to be up
notify-send 'Waiting for network...'
while ! systemctl is-active --quiet network-online.target; do sleep 1; done
notify-send 'Network found.'

# Wait for the Emacs daemon
notify-send 'Starting Emacs...'
/run/current-system/sw/bin/emacsclient -a "" -e '(progn)' &

# Wait for Emacs daemon to be ready
while ! /run/current-system/sw/bin/emacsclient -e '(progn)' &>/dev/null; do
  sleep 1
done
notify-send 'Emacs daemon started.'

# Desktop 1
# Email, Calendar, News (General)
bspc rule -a Google-chrome -o desktop='^1'
/etc/profiles/per-user/%USER%/bin/google-chrome-stable "https://www.fastmail.com" "https://calendar.google.com/calendar/u/0/r" &!

sleep 1

bspc rule -a Google-chrome -o desktop='^1'
/etc/profiles/per-user/%USER%/bin/google-chrome-stable --new-window "https://www.techmeme.com" "https://www.inoreader.com/" &!

sleep 1

# Desktop 2
# Terminal, Emacs (IDE)
bspc rule -a Alacritty -o desktop='^2'
/etc/profiles/per-user/%USER%/bin/alacritty -e sh -c 'tmux attach || tmux new-session' &

sleep 1

bspc rule -a Emacs -o desktop='^2'
/run/current-system/sw/bin/emacsclient -c &!

sleep .5

# Desktop 3
# ChatGPT, Emacs
bspc rule -a Google-chrome -o desktop='^3'
/etc/profiles/per-user/%USER%/bin/google-chrome-stable --new-window "https://chat.openai.com" &!

sleep .5

bspc rule -a Emacs -o desktop='^3'
/run/current-system/sw/bin/emacsclient -c &!

sleep .5

# Desktop 5
# Apple Music, Emacs
bspc rule -a Cider -o desktop='^5'
/etc/profiles/per-user/%USER%/bin/cider &!

sleep 1

#bspc rule -a Emacs -o desktop='^5'
#/run/current-system/sw/bin/emacsclient -c &!
