#!/bin/sh -e

VERSION=1.0

YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

FLAKE="Dustins-MBP"
SYSTEM="darwinConfigurations.$FLAKE.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
nix --experimental-features 'nix-command flakes' build .#$SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
