# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Root
  fileSystems."/" =
    { device = "rpool/root/nixos";
      fsType = "zfs";
    };
  # Docker user configuration
  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  # Docker volumes
  fileSystems."/var/lib/docker" =
    { device = "rpool/data";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
