#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

FLAKE="macos"
SYSTEM="darwinConfigurations.$FLAKE.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}(Dry run)${GREEN} Starting build...${NC}"
nix --experimental-features 'nix-command flakes' build .#$SYSTEM $@

echo "${YELLOW}(Dry run)${GREEN} Switching to new generation...${NC}"

echo "${YELLOW}(Dry run)${GREEN} Cleaning up...${NC}"
unlink ./result

echo "${YELLOW}(Dry run)${GREEN} Switch to new generation complete!${NC}"
