#!/usr/bin/env bash
set -e

unmount_usb() {
  if mountpoint -q /mnt/usb; then
    sudo umount /mnt/usb
  fi
}

mount_usb() {
  if mountpoint -q /mnt/usb; then
    echo -e "\e[0;32mUSB drive already mounted.\e[0m"
  else
    for dev in sdc sdd sde sdf sdg sdh sdi sdj sdk sdl; do
      if sudo blkid /dev/$dev | grep -iq 'TYPE="vfat"'; then
        mkdir -p /mnt/usb
        sudo mount /dev/$dev /mnt/usb && { echo -e "\e[0;32mUSB drive mounted successfully on /dev/$dev.\e[0m"; break; } || echo -e "\e[0;31mFailed to mount /dev/$dev.\e[0m"
      fi
    done
  fi
}

setup_ssh_directory() {
  export SSH_DIR=/root/.ssh
  mkdir -p $SSH_DIR
}

copy_keys() {
  cp /mnt/usb/id_ed25519_agenix.pub $SSH_DIR
  cp /mnt/usb/id_ed25519_agenix $SSH_DIR
  chmod 600 $SSH_DIR/id_ed25519_{agenix,agenix.pub}
}

set_keys() {
  cp /mnt/usb/id_ed25519_github.pub $SSH_DIR/id_ed25519.pub
  cp /mnt/usb/id_ed25519_github $SSH_DIR/id_ed25519
  chmod 600 $SSH_DIR/id_ed25519
  chmod 644 $SSH_DIR/id_ed25519.pub
}

change_ownership() {
  chown nixos:wheel $SSH_DIR/id_ed25519{,.pub}
  chown nixos:wheel $SSH_DIR/id_ed25519_{agenix,agenix.pub}
}

trap unmount_usb EXIT

setup_ssh_directory
mount_usb
copy_keys
set_keys
change_ownership
unmount_usb

