#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

username=${USER}
export SSH_DIR=/Users/${username}/.ssh

setup_ssh_directory() {
  mkdir -p ${SSH_DIR}
}

check_existing_keys() {
  if [[ -f "${SSH_DIR}/id_ed25519" || -f "${SSH_DIR}/id_ed25519_agenix" ]]; then
    echo -e "${RED}Existing SSH keys found.${NC}"
    echo -e "${RED}1) id_ed25519${NC}"
    [[ -f "${SSH_DIR}/id_ed25519" ]] && cat "${SSH_DIR}/id_ed25519.pub"
    echo -e "${RED}2) id_ed25519_agenix${NC}"
    [[ -f "${SSH_DIR}/id_ed25519_agenix" ]] && cat "${SSH_DIR}/id_ed25519_agenix.pub"
    read -p "Do you want to replace them? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 0
    else
      return 1
    fi
  fi
  return 0
}

generate_keys() {
  ssh-keygen -t ed25519 -f "${SSH_DIR}/id_ed25519" -N ""
  ssh-keygen -t ed25519 -f "${SSH_DIR}/id_ed25519_agenix" -N ""
  chown ${username}:staff ${SSH_DIR}/id_ed25519{,_agenix}{,.pub}
}

setup_ssh_directory
if check_existing_keys; then
  generate_keys
  echo -e "${GREEN}New SSH keys have been generated.${NC}"
else
  echo -e "${GREEN}Existing SSH keys kept.${NC}"
fi

echo -e "${GREEN}1) Add the id_ed25519 key to Github.${NC}"
cat "${SSH_DIR}/id_ed25519.pub"
echo -e "${GREEN}2) Create a private nix-secrets repo in Github, even if it's empty.${NC}"
