#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor --reset-desktops daily dev chat media finance misc
bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Padding outside of the window
bspc config top_padding            60
bspc config bottom_padding         60
bspc config left_padding           60
bspc config right_padding          60

# Move floating windows
bspc config pointer_action1 move

# Resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a discord desktop='chat' follow=on
bspc rule -a google-chrome-stable desktop='daily' follow=on
bspc rule -a vlc desktop='media' follow=on
bspc rule -a spotify desktop='media' follow=on
bspc rule -a keepassxc state=floating follow=on
bspc rule -a feh state=floating

# Set background and top bar
feh --bg-scale $HOME/.config/wallpaper/active.png
systemctl --user start polybar
