#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor --reset-desktops daily dev chat media finance system
bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Padding outside of the window
bspc config top_padding            60
bspc config bottom_padding         60
bspc config left_padding           60
bspc config right_padding          60

# Move floating windows
bspc config pointer_action1 move

# Resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Discord desktop='chat' follow=on
bspc rule -a vlc state=floating desktop='media' follow=on
bspc rule -a Cider desktop='media' follow=on
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a feh state=floating
bspc rule -a Peek state=floating follow=on

## Set desktops
killall -qw google-chrome-stable
killall -qw tmux
killall -qw emacsclient
killall -qw slack
killall -qw telegram-desktop
killall -qw cider
killall -qw btop
killall -qw pcmanfm
bspc rule -a google-chrome-stable -o desktop='daily' && /etc/profiles/per-user/dustin/bin/google-chrome-stable "https://calendar.google.com/calendar/u/0/r" "https://www.fastmail.com"
bspc rule -a google-chrome-stable -o desktop='daily' && /etc/profiles/per-user/dustin/bin/google-chrome-stable "https://www.techmeme.com" "https://news.ycombinator.com/"
bspc rule -a google-chrome-stable -o desktop='finance' && /etc/profiles/per-user/dustin/bin/google-chrome-stable "https://www.tradingview.com" "https://www.bloomberg.com"
bspc rule -a Alacritty -o desktop='dev' && /etc/profiles/per-user/dustin/bin/alacritty -e tmux
bspc rule -a emacs -o desktop='dev' && /run/current-system/sw/bin/emacsclient -c
bspc rule -a Slack -o desktop='chat' && /etc/profiles/per-user/dustin/bin/slack
bspc rule -a Telegram -o desktop='chat' && /etc/profiles/per-user/dustin/bin/telegram-desktop
bspc rule -a cider -o desktop='media' && /etc/profiles/per-user/dustin/bin/cider
bspc rule -a Alacritty -o desktop='system' && /etc/profiles/per-user/dustin/bin/alacritty -e btop
bspc rule -a pcmanfm -o desktop='system' && /etc/profiles/per-user/dustin/bin/pcmanfm

# Set background and top bar
feh --bg-scale $HOME/.config/wallpaper/active.png
systemctl --user start polybar
